# Generated by Django 4.1.4 on 2023-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_Whatsapp', models.URLField(verbose_name='Ссылка на Whatsapp')),
                ('link_Telegram', models.URLField(verbose_name='Ссылка на Telegram')),
                ('aboutText', models.TextField(max_length=200, verbose_name='Текст о нас')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
