# Generated by Django 4.2.1 on 2023-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_productcard_alter_post_title_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
