# Generated by Django 4.1.4 on 2023-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutText',
            field=models.TextField(verbose_name='Текст о нас'),
        ),
    ]
